
version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     restart: unless-stopped
     volumes:
       - wordpress_files:/var/www/html
     networks:
       - app-network
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: pass123

   db:
     image: mysql:5.7
     container_name: db
     restart: unless-stopped
     volumes:
       - db_data:/var/lib/mysql
     networks:
       - app-network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: pass123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: pass123
volumes:
    wordpress_files:
    db_data:

networks:
  app-network:
    driver: bridge  
